version: '2'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '5432:5432'
    volumes: 
      - /var/lib/postgresql/data