version: "2"
services:
  app:
    build: ./app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env
    depends_on:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h db -p 5432 -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
